### ISSUE TITLE
Multiple Code Style Issues

### ISSUE THREAD

**Issue by thomasfire** [rbetik12/FlexLibrary#1]
At function `DeleteOneCharacter` interface enhancement and unification by passing cursorPos via const pointer. 
Then, at functions `WriteOneCharacter` and `DeleteOneCharacter` create a buffer to store `cursorPos->X` in order to avoid dereference. In both functions `memmove` could be used without unnecessary `calloc`'s and `free`'s.

**Comment by rbetik12** [comment]
Closed the issue due to complete code rewrtiting.
